version: "3.8"

services:
  backend:
    image: ansible:5000/tokenpass_backend:latest
    ports:
      - "4000:4000"
    deploy:
      placement:
        constraints:
          - node.hostname == docker1.us-central1-c.c.project-aaa5bfcd-8332-4e85-bd0.internal
    networks:
      - tokenpass_net

  frontend:
    image: ansible:5000/tokenpass_frontend:latest
    ports:
      - "3000:3000"
    deploy:
      placement:
        constraints:
          - node.hostname == docker2.us-central1-c.c.project-aaa5bfcd-8332-4e85-bd0.internal
    networks:
      - tokenpass_net

networks:
  tokenpass_net:
    driver: overlay
